-- =========================================================
-- Loop-Ad Expedia Demo Seed
-- Purpose:
--   - Create demo service hierarchy for Decision analysis.
--   - Do not seed runtime results such as analyses, suggestions, runs, or assignments.
-- =========================================================

BEGIN;

INSERT INTO projects (
    project_id,
    project_name,
    domain,
    write_key,
    industry,
    status,
    updated_at
)
VALUES (
    'demo_project',
    'LoopAd Expedia Hotel Demo',
    'demo.loopad.local',
    'demo_write_key_expedia',
    'hotel_booking',
    'active',
    now()
)
ON CONFLICT (project_id) DO UPDATE SET
    project_name = EXCLUDED.project_name,
    domain = EXCLUDED.domain,
    write_key = EXCLUDED.write_key,
    industry = EXCLUDED.industry,
    status = EXCLUDED.status,
    updated_at = now();

INSERT INTO campaigns (
    campaign_id,
    project_id,
    name,
    objective,
    target_audience,
    start_date,
    end_date,
    primary_metric,
    status,
    updated_at
)
VALUES (
    'camp_expedia_hotel_demo',
    'demo_project',
    'Expedia Hotel Booking Demo Campaign',
    'Use Expedia hotel behavior data to demonstrate AI segment suggestion and promotion loop.',
    'existing_users',
    CURRENT_DATE,
    CURRENT_DATE + 30,
    'booking_conversion_rate',
    'active',
    now()
)
ON CONFLICT (campaign_id) DO UPDATE SET
    project_id = EXCLUDED.project_id,
    name = EXCLUDED.name,
    objective = EXCLUDED.objective,
    target_audience = EXCLUDED.target_audience,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    primary_metric = EXCLUDED.primary_metric,
    status = EXCLUDED.status,
    updated_at = now();

INSERT INTO promotions (
    promotion_id,
    project_id,
    campaign_id,
    channel,
    marketing_theme,
    target_audience,
    goal_metric,
    goal_target_value,
    goal_basis,
    min_sample_size,
    max_loop_count,
    message_brief,
    offer_type,
    landing_url,
    landing_type,
    budget_json,
    metadata_json,
    status,
    updated_at
)
VALUES
(
    'promo_expedia_email_reactivation',
    'demo_project',
    'camp_expedia_hotel_demo',
    'email',
    'hotel_reactivation',
    'existing_users',
    'booking_conversion_rate',
    0.050000,
    'all_segments',
    100,
    3,
    'Reactivate users with high hotel booking propensity using personalized email content.',
    'limited_time_discount',
    'https://demo.loopad.local/hotels',
    'search_page',
    '{"currency": "KRW", "max_daily_budget": 500000}'::jsonb,
    '{"dataset": "kaggle_expedia_hotel_recommendations", "demo": true, "scenario": "email_reactivation"}'::jsonb,
    'analysis_ready',
    now()
),
(
    'promo_expedia_onsite_last_minute',
    'demo_project',
    'camp_expedia_hotel_demo',
    'onsite_banner',
    'last_minute_hotel',
    'existing_users',
    'inflow_rate',
    0.080000,
    'all_segments',
    100,
    3,
    'Show onsite banner to users with near check-in intent and strong hotel browsing behavior.',
    'last_minute_deal',
    'https://demo.loopad.local/hotels/last-minute',
    'hotel_detail_page',
    '{"currency": "KRW", "max_daily_budget": 500000}'::jsonb,
    '{"dataset": "kaggle_expedia_hotel_recommendations", "demo": true, "scenario": "onsite_last_minute"}'::jsonb,
    'analysis_ready',
    now()
),
(
    'promo_expedia_sms_near_checkin',
    'demo_project',
    'camp_expedia_hotel_demo',
    'sms',
    'near_checkin_reminder',
    'existing_users',
    'booking_conversion_rate',
    0.040000,
    'all_segments',
    100,
    3,
    'Send concise SMS offers to users with near check-in hotel search patterns.',
    'mobile_coupon',
    'https://demo.loopad.local/hotels/mobile-offer',
    'booking_resume',
    '{"currency": "KRW", "max_daily_budget": 500000}'::jsonb,
    '{"dataset": "kaggle_expedia_hotel_recommendations", "demo": true, "scenario": "sms_near_checkin"}'::jsonb,
    'analysis_ready',
    now()
)
ON CONFLICT (promotion_id) DO UPDATE SET
    project_id = EXCLUDED.project_id,
    campaign_id = EXCLUDED.campaign_id,
    channel = EXCLUDED.channel,
    marketing_theme = EXCLUDED.marketing_theme,
    target_audience = EXCLUDED.target_audience,
    goal_metric = EXCLUDED.goal_metric,
    goal_target_value = EXCLUDED.goal_target_value,
    goal_basis = EXCLUDED.goal_basis,
    min_sample_size = EXCLUDED.min_sample_size,
    max_loop_count = EXCLUDED.max_loop_count,
    message_brief = EXCLUDED.message_brief,
    offer_type = EXCLUDED.offer_type,
    landing_url = EXCLUDED.landing_url,
    landing_type = EXCLUDED.landing_type,
    budget_json = EXCLUDED.budget_json,
    metadata_json = EXCLUDED.metadata_json,
    status = EXCLUDED.status,
    updated_at = now();

INSERT INTO segment_definitions (
    segment_id,
    project_id,
    campaign_id,
    promotion_id,
    segment_name,
    source,
    query_preview_id,
    natural_language_query,
    generated_sql,
    rule_json,
    profile_json,
    sample_size,
    total_eligible_user_count,
    sample_ratio,
    status,
    updated_at
)
VALUES
(
    'seg_existing_all',
    'demo_project',
    NULL,
    NULL,
    'All Existing Hotel Users',
    'system_default',
    NULL,
    '전체 기존 호텔 사용자',
    NULL,
    '{"type": "all_users"}'::jsonb,
    '{"description": "전체 기존 호텔 사용자", "expedia_feature_hint": "all historical users"}'::jsonb,
    0,
    0,
    0,
    'active',
    now()
),
(
    'seg_mobile_user',
    'demo_project',
    NULL,
    NULL,
    'Mobile Hotel Browsers',
    'system_default',
    NULL,
    '모바일에서 호텔을 탐색하는 사용자',
    NULL,
    '{"type": "field_filter", "field": "is_mobile", "operator": "eq", "value": 1}'::jsonb,
    '{"description": "모바일에서 호텔을 탐색하는 사용자", "expedia_feature_hint": "is_mobile = 1"}'::jsonb,
    0,
    0,
    0,
    'active',
    now()
),
(
    'seg_family_trip',
    'demo_project',
    NULL,
    NULL,
    'Family Trip Searchers',
    'system_default',
    NULL,
    '자녀 동반 검색이 있는 가족 여행 사용자',
    NULL,
    '{"type": "field_filter", "field": "srch_children_cnt", "operator": "gt", "value": 0}'::jsonb,
    '{"description": "자녀 동반 검색이 있는 가족 여행 사용자", "expedia_feature_hint": "srch_children_cnt > 0"}'::jsonb,
    0,
    0,
    0,
    'active',
    now()
),
(
    'seg_package_trip',
    'demo_project',
    NULL,
    NULL,
    'Package Trip Searchers',
    'system_default',
    NULL,
    '패키지 여행 검색 사용자',
    NULL,
    '{"type": "field_filter", "field": "is_package", "operator": "eq", "value": 1}'::jsonb,
    '{"description": "패키지 여행 검색 사용자", "expedia_feature_hint": "is_package = 1"}'::jsonb,
    0,
    0,
    0,
    'active',
    now()
),
(
    'seg_near_checkin',
    'demo_project',
    NULL,
    NULL,
    'Near Check-in Searchers',
    'system_default',
    NULL,
    '체크인 날짜가 가까운 사용자',
    NULL,
    '{"type": "date_diff_filter", "field": "srch_ci", "base_field": "date_time", "unit": "day", "operator": "between", "value": [0, 7]}'::jsonb,
    '{"description": "체크인 날짜가 가까운 사용자", "expedia_feature_hint": "days_until_checkin between 0 and 7"}'::jsonb,
    0,
    0,
    0,
    'active',
    now()
),
(
    'seg_long_stay',
    'demo_project',
    NULL,
    NULL,
    'Long Stay Searchers',
    'system_default',
    NULL,
    '장기 숙박 검색 사용자',
    NULL,
    '{"type": "date_diff_filter", "from_field": "srch_ci", "to_field": "srch_co", "unit": "day", "operator": "gte", "value": 4}'::jsonb,
    '{"description": "장기 숙박 검색 사용자", "expedia_feature_hint": "stay_nights >= 4"}'::jsonb,
    0,
    0,
    0,
    'active',
    now()
),
(
    'seg_couple_trip',
    'demo_project',
    NULL,
    NULL,
    'Couple Trip Searchers',
    'system_default',
    NULL,
    '성인 2명, 자녀 0명, 객실 1개 조건의 커플 여행 후보',
    NULL,
    '{"type": "and", "conditions": [{"field": "srch_adults_cnt", "operator": "eq", "value": 2}, {"field": "srch_children_cnt", "operator": "eq", "value": 0}, {"field": "srch_rm_cnt", "operator": "eq", "value": 1}]}'::jsonb,
    '{"description": "성인 2명, 자녀 0명, 객실 1개 조건의 커플 여행 후보", "expedia_feature_hint": "adults=2, children=0, room=1"}'::jsonb,
    0,
    0,
    0,
    'active',
    now()
),
(
    'seg_repeat_hotel_no_booking',
    'demo_project',
    NULL,
    NULL,
    'Repeat Hotel Browsers Without Recent Booking',
    'system_default',
    NULL,
    '호텔 탐색은 반복했지만 최근 예약은 없는 사용자',
    NULL,
    '{"type": "aggregate_filter", "conditions": [{"metric": "event_count", "operator": "gte", "value": 2}, {"metric": "booking_rate", "operator": "eq", "value": 0}]}'::jsonb,
    '{"description": "호텔 탐색은 반복했지만 최근 예약은 없는 사용자", "expedia_feature_hint": "event_count >= 2 and booking_rate = 0"}'::jsonb,
    0,
    0,
    0,
    'active',
    now()
)
ON CONFLICT (segment_id) DO UPDATE SET
    project_id = EXCLUDED.project_id,
    campaign_id = EXCLUDED.campaign_id,
    promotion_id = EXCLUDED.promotion_id,
    segment_name = EXCLUDED.segment_name,
    source = EXCLUDED.source,
    query_preview_id = EXCLUDED.query_preview_id,
    natural_language_query = EXCLUDED.natural_language_query,
    generated_sql = EXCLUDED.generated_sql,
    rule_json = EXCLUDED.rule_json,
    profile_json = EXCLUDED.profile_json,
    sample_size = EXCLUDED.sample_size,
    total_eligible_user_count = EXCLUDED.total_eligible_user_count,
    sample_ratio = EXCLUDED.sample_ratio,
    status = EXCLUDED.status,
    updated_at = now();

COMMIT;
